config/routes.rb
Rails.application.routes.draw do

  root 'store#home'
  get 'store/home'
  get 'store/products_category/:id' => 'store#products_category'
  get 'store/products/:id' => 'store#product_detail'
  get 'users/:id' => 'users#show'
  patch 'users/:id' => 'users#update'

  post   'signin'   => 'sessions#signin'
  post   'signup'   => 'sessions#signup'
  post   'signout'  => 'sessions#signout'
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="container-fluid content-breather" id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-underline">Rails Sample API Client Application</h3>
            </div>
        </div>
    </div><!-- End of container -->
</div><!-- End of fluid container --> 

app/views/layouts/_header.html.erb
<nav class="navbar" >
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to image_tag("logo.jpg", size:"60x60" ), {action: 'home', controller: 'store'}, class: 'navbar-brand' %>
      <%= link_to "Rails Sample API Client Application", {action: 'home', controller: 'store'}, class: 'navbar-brand' %>
    </div><!-- End of navbar header -->
    <div class="collapse navbar-collapse" >
      <ul class="nav navbar-nav navbar-right">
        <li class="active">
          <%= link_to "Home", root_path %>
        </li>       	
        <% if current_user %>
        <li id='list_profile' class="">
            <% current_user_id = current_user['user_id'] if current_user %>
            <%= link_to "Profile", {action: 'show', controller: 'users', id: current_user_id } %>
        </li>       	
        <li id='list_sign_out' class="">
          <%#= link_to "Sign Out", signout_path, :method=>:post, :remote => true  %>
          <%= link_to "Sign Out", signout_path, :method=>:post  %>
        </li>       	
        <% else %>
        <li id='list_sign_in' class="">
          <a href="#modal-sign-in" class="" data-toggle="modal" data-target="#modal-sign-in">Sign In</a>
        </li>       	
        <li id='list_sign_up' class="">
          <a href="#modal-sign-up" class="" data-toggle="modal" data-target="#modal-sign-up">Sign Up</a>
        </li>       	
        <% end %>
      </ul>

    </div><!-- End of nav-collapse -->                
    <div class="collapse navbar-collapse" >
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= ('Hello '+ (current_user['first_name']?current_user['first_name']:'')) if current_user %>
        </li>       	
      </ul>
    </div>
  </div><!-- End of container class -->
</nav><!-- End of navigation -->


<script>
$(document).ready(function () {
  <%# if logged_in? %>
    //$('#list_sign_out').show();
    //$('#list_sign_in').hide();
    //$('#list_sign_up').hide();
  <%# else %>
    //$('#list_sign_out').hide();
    //$('#list_sign_in').show();
    //$('#list_sign_up').show();
  <%# end %>
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Rails API Client Application</title>
        
  <!-- Meta tags -->
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
			
  <%-#<link rel="stylesheet" href="{{asset('bundles/app/css/my_style.css')}}"> %>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <!-- Jquery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
<body>

  <div > <!-- Start of global wrapper -->

    <%= render "layouts/header" %>
    <%=yield %>
    <%= render "layouts/footer" %>

    <!-- begin:modal-sign-in -->
    <div class="modal fade" id="modal-sign-in" tabindex="-1" role="dialog" aria-labelledby="modal-sign-in" aria-hidden="true">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">

          <%#= form_for(:session, url: signin_path, remote: true) do|f| %>
          <%= form_for(:session, url: signin_path) do|f| %>
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title">Sign In</h4> 
            </div>
            <div class="modal-body">
              <p style="color:red" id="err_sign_in"></p>
              <div class="form-group">
                <input type='text' id='log_in_email' name='email' class='form-control' placeholder='Email address' />
              </div>
              <div class="form-group">
               <input type='password' id='log_in_password' name='password' class='form-control' placeholder='Password' />
              </div>
            </div>
            <div class="modal-footer  text-left">
              <input id='btn_sign_in' type='submit' name='btn_submit' class='btn branding-background btn-block btn-lg' value='Sign In' />
            </div>
          <% end %>

        </div>
      </div>
    </div>

    <!-- begin:modal-signup -->
    <div class="modal fade" id="modal-sign-up" tabindex="-1" role="dialog" aria-labelledby="modal-sign-up" aria-hidden="true">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">

          <%#= form_for(:session, url: signup_path, remote: true) do|f| %>
          <%= form_for(:session, url: signup_path) do|f| %>
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title">Sign Up</h4> 
            </div>
            <div class="modal-body">
              <p style="color:red" id="err_sign_up"></p>
              <div class="row form-group">
                <div class="col-md-6">
                  <input type='text' id='first_name' name='first_name' class='form-control' placeholder='First Name' />
                </div>
                <div class="col-md-6">
                  <input type='text' id='last_name' name='last_name' class='form-control' placeholder='Last Name' />
                </div>
              </div>
              <p style="color:red" id="err_eamil_exists"></p>
              <div class="form-group">
                  <input type='text' id='email' name='email' class='form-control' placeholder='Email address' />
                </div>
                <div class="form-group">
                  <input type='password' id='password' name='password' class='form-control' placeholder='Password' />
                </div>
                <div class="form-group">
                  <input type='password' id='password_confirmation' name='password_confirmation' class='form-control' placeholder='Confirm Password' />
                </div>
              </div>
              <div class="modal-footer text-left">
                <input type='submit' class='btn branding-background btn-block btn-lg' value='Sign Up' />
              </div>
          <% end %>

        </div>
      </div>
    </div>

  </div> <!-- End of global wrapper -->


</body>
</html>